//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLuong
    {
        public int MaBangL { get; set; }
        public Nullable<int> MaCCTL { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public double HSL { get; set; }
        public double HSPC { get; set; }
        public Nullable<int> MaMLTT { get; set; }
        public int MucLuongTTV { get; set; }
        public double MucLuongTTC { get; set; }
        public double NgayCong { get; set; }
        public double MucLuongCoSo { get; set; }
        public double PhuCapTTCV { get; set; }
        public double TienLuongBQMN { get; set; }
        public double LuongThoiGian { get; set; }
        public float NgayHuongCong100PT { get; set; }
        public double TienAnGiuaCa { get; set; }
        public float CongK3 { get; set; }
        public double TienK3 { get; set; }
        public Nullable<float> CongTgNgayThuong { get; set; }
        public Nullable<float> CongTGNgayNghi { get; set; }
        public Nullable<float> CongTGNgayLe { get; set; }
        public Nullable<double> TienThuong { get; set; }
        public Nullable<int> MaDMXX { get; set; }
        public Nullable<double> LeTet { get; set; }
        public string GhiChuLeTet { get; set; }
        public double TongLuong { get; set; }
        public double TruBHYT { get; set; }
        public double TruBHXH { get; set; }
        public double TruBHTN { get; set; }
        public double SoTienConNhan { get; set; }
        public int MucThue { get; set; }
        public double ThuePhaiNop { get; set; }
        public double ThueCaNam { get; set; }
        public Nullable<double> TamUng { get; set; }
        public double TongThucNhan { get; set; }
        public Nullable<int> MaPB { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaND { get; set; }
    
        public virtual ChamCongTL ChamCongTL { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        public virtual DinhMucXangXe DinhMucXangXe { get; set; }
        public virtual MucLuongToiThieu MucLuongToiThieu { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
