//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCongTL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChamCongTL()
        {
            this.BangLuong = new HashSet<BangLuong>();
        }
    
        public int MaCCTL { get; set; }
        public string TenCCTL { get; set; }
        public int Nam { get; set; }
        public int Thang { get; set; }
        public Nullable<bool> Khoa { get; set; }
        public Nullable<System.DateTime> NgayTinhCong { get; set; }
        public Nullable<double> NgayCongTrongThang { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangLuong> BangLuong { get; set; }
    }
}
