//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChungChi
    {
        public int MaCC { get; set; }
        public string TenCC { get; set; }
        public Nullable<int> MaNV { get; set; }
        public System.DateTime NgayCap { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public string NoiCap { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
