//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DienBienTrangThaiLamViec
    {
        public int MaDBTTLV { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<int> MaPB { get; set; }
        public Nullable<int> MaCV { get; set; }
        public Nullable<int> MaTTLV { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime TuNgay { get; set; }
        public System.DateTime DenNgay { get; set; }
        public string SoQD { get; set; }
        public System.DateTime NgayQD { get; set; }
        public int TroCapThoiViec { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual TrangThaiLamViec TrangThaiLamViec { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
