//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaHanHopDong
    {
        public int MaGHHD { get; set; }
        public System.DateTime NgayGiaHan { get; set; }
        public System.DateTime NgayHetHanCu { get; set; }
        public System.DateTime NgayHetHanMoi { get; set; }
        public Nullable<int> MaHD { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string GhiChu { get; set; }
    
        public virtual HopDong HopDong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
