//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeSoThangBacLuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeSoThangBacLuong()
        {
            this.DieuChuyenCongTac = new HashSet<DieuChuyenCongTac>();
            this.HopDong = new HashSet<HopDong>();
            this.QuaTrinhLuong = new HashSet<QuaTrinhLuong>();
        }
    
        public int MaBL { get; set; }
        public Nullable<int> MATL { get; set; }
        public System.DateTime NgayQD { get; set; }
        public Nullable<double> Bac1 { get; set; }
        public Nullable<double> Bac2 { get; set; }
        public Nullable<double> Bac3 { get; set; }
        public Nullable<double> Bac4 { get; set; }
        public Nullable<double> Bac5 { get; set; }
        public Nullable<double> Bac6 { get; set; }
        public Nullable<double> Bac7 { get; set; }
        public Nullable<double> Bac8 { get; set; }
        public Nullable<double> Bac9 { get; set; }
        public Nullable<double> Bac10 { get; set; }
        public Nullable<double> Bac11 { get; set; }
        public Nullable<double> Bac12 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DieuChuyenCongTac> DieuChuyenCongTac { get; set; }
        public virtual ThangLuong ThangLuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhLuong> QuaTrinhLuong { get; set; }
    }
}
