//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.DieuChuyenCongTac = new HashSet<DieuChuyenCongTac>();
            this.GiaHanHopDong = new HashSet<GiaHanHopDong>();
        }
    
        public int MaHD { get; set; }
        public Nullable<int> MaLoaiHD { get; set; }
        public Nullable<int> MaNV { get; set; }
        public System.DateTime NgayKy { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public int ThoiHan { get; set; }
        public string NguoiKy { get; set; }
        public Nullable<int> MaBL { get; set; }
        public Nullable<int> MaTL { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        public string NoiCap { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DieuChuyenCongTac> DieuChuyenCongTac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiaHanHopDong> GiaHanHopDong { get; set; }
        public virtual HeSoThangBacLuong HeSoThangBacLuong { get; set; }
        public virtual LoaiHopDong LoaiHopDong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual ThangLuong ThangLuong { get; set; }
    }
}
