//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhenThuongKyLuat
    {
        public int MaHD { get; set; }
        public int SoQD { get; set; }
        public System.DateTime NgayQD { get; set; }
        public string TenKTKL { get; set; }
        public string LyDo { get; set; }
        public string HinhThuc { get; set; }
        public string DonviKTKL { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
