//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaTrinhLuong
    {
        public int MaQTL { get; set; }
        public System.DateTime NgayQD { get; set; }
        public System.DateTime NgayHuong { get; set; }
        public System.DateTime NgayNangCapLuong { get; set; }
        public Nullable<int> MaBL { get; set; }
        public Nullable<double> HSL { get; set; }
        public Nullable<double> HSPC { get; set; }
        public Nullable<int> MaMLTT { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual HeSoThangBacLuong HeSoThangBacLuong { get; set; }
        public virtual MucLuongToiThieu MucLuongToiThieu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
